const PROJECTS_DATA = [
  {
    id: 1,
    name: "Infrastructure Monitoring System",
    desc: "Real-time monitoring using Grafana, Prometheus, Docker, and K8s.",
    image: "/images/7.jpg",
    tech: [
      { class: "fab fa-react", name: "React" },
      { class: "/images/docker.svg", name: "Docker" },
      { class: "/images/kubernetes.svg", name: "Grafana" },
    ],
    date: "Dec, 2024",
    link: "https://github.com/Shivam327/Infrastructure-Monitoring",
    type: "Infrastructure",
  },
  {
    id: 2,
    name: "Used Car API",
    desc: "Backend API with NestJS, PostgreSQL, and TypeORM.",
    image: "/images/2.jpg",
    tech: [
      { class: "/images/nestjs.svg", name: "NestJS" },
      { class: "/images/postgresql.svg", name: "PostgreSQL" },
    ],
    date: "Nov, 2024",
    link: "https://github.com/Shivam327/Used-car-API-NestJS",
    type: "Backend API",
  },
  {
    id: 3,
    name: "TrackerX",
    desc: "TrackerX is a Full-stack MERN Application for managing finances. I build this App for personal use, I was not able to find an app for managing finances which can fulfill my needs So, I decided to build my own 😋. User can track their expenses and income with various Filter Options. I used React-Bootstrap to build User Interface, Redux to manage state, Express for Backend API server, MongoDB Atlas as Database.",
    image: "/images/2.jpg",
    tech: [
      { class: "fab fa-react", name: "React" },
      { class: "/images/redux.svg", name: "Redux" },
      { class: "/images/expressjs.svg", name: "Express" },
      { class: "/images/nodejs.svg", name: "Node" },
      { class: "/images/mongodb.svg", name: "MongoDB" },
    ],
    date: "--",
    link: "Coming Soon...",
    type: "WebApp",
  },
  {
    id: 4,
    name: "My Portfolio 2021",
    desc: "This is the website that I love the most. This is my Portfolio website 2021. This website contains about me and my projects. I used React and GSAP to build this website.",
    image: "/images/4.jpg",
    tech: [
      { class: "fab fa-react", name: "React" },
      { class: "/images/gsap.svg", name: "GSAP" },
    ],
    date: "--",
    link: "--",
    type: "WebSite",
  },
  {
    id: 5,
    name: "TrackIt",
    desc: "TrackIt is web application by which users can track Covid Cases and Weather on interacting with Map.",
    image: "/images/7.jpg",
    tech: [
      { class: "/images/javascript.svg", name: "JS" },
      { class: "/images/html5.svg", name: "HTML" },
      { class: "/images/css.svg", name: "CSS" },
    ],
    date: "--",
    link: "",
    type: "WebApp",
  },
  {
    id: 6,
    name: "My Portfolio 2019",
    desc: "This was my portfolio website in 2019.",
    image: "/images/6.jpg",
    tech: [
      { class: "fab fa-react", name: "React" },
      { class: "/images/redux.svg", name: "Redux" },
    ],
    date: "Aug, 2019",
    link: "",
    type: "WebSite",
  },
];

export default PROJECTS_DATA;
